name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12.x
          check-latest: true

      - name: Install Dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run type check
        run: npm run type-check

      - name: Build
        run: npm run build
